authentication/config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  get 'login' , to:"session#new"
  get 'logout', to: 'session#destroy'
  get 'register' , to:"user#new"
  resources :user , only:[:create]

  resources :session , only:[:create]

end

authentication/app/models/user.rb
class User < ApplicationRecord
    validates :password,confirmation:true, presence: true ,length: { minimum: 5 }
    validates :terms, :acceptance => true
    validates :email , presence: true , uniqueness: true 


    def terms
        @terms
    end

    def terms=(raw)
        @terms = raw == 'on'? '1' : '0;'
    end

    def password
        @password
      end
    
    def password=(raw)
        @password = raw
        self.password_digest = BCrypt::Password.create(raw)
    end
    
    def is_password?(raw)
        BCrypt::Password.new(password_digest).is_password?(raw)
    end

end

authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def current_user
      if session[:user_id]
        @user = User.find(session[:user_id])
      end
    end
  
    def logged_in?
      !!current_user
    end
  
    def authorized
      redirect_to login_path unless logged_in?
    end

    def ensure_current_user
        if logged_in?
          redirect_to "/"
        end
    end
end

authentication/app/controllers/public_controller.rb
class PublicController < ApplicationController
  before_action :authorized

  def index
  end
end

authentication/app/controllers/session_controller.rb
class SessionController < ApplicationController

  before_action :ensure_current_user, only: [:new]

  def new
    @user = User.new()
  end

  def create
    @user = User.find_by(email: user_params[:email])

    if @user && @user.is_password?(user_params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash.now[:notice] = "Invalid email or password"
      render :new, status: 404
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

authentication/app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :ensure_current_user

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url
    else
      render :new, status: 422
    end
    
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :terms)
  end

  def not_found
    render "404.html", status: 404
  end

  
end

authentication/app/helpers/session_helper.rb
module SessionHelper
end

authentication/app/helpers/user_helper.rb
module UserHelper
end

authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class=" ">
    <% if current_user %>
      Hi <%= current_user.email %>
      <%= link_to "Log out", logout_path %>
    <% end %>
      <%= yield %>
    </main>
  </body>
</html>

authentication/app/views/session/new.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
          <img class="w-8 h-8 mr-2" src="https://i.ibb.co/PMNCc2v/Screen-Shot-2022-10-11-at-15-08-55.png"  alt="logo">
          100Projects    
      </a>
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">

              <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                  Sign in to your account
              </h1>
              <p class="text-red-700"><%= notice %></p>

              <form class="space-y-4 md:space-y-6" action="/session" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                  <div>
                      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                      <input type="email" name="user[email]" id="email"  class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="">
                  </div>
                  <div>
                      <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                      <input type="password" name="user[password]" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                  </div>
                  <div class="flex items-center justify-between">
                      <div class="flex items-start">
                          <div class="flex items-center h-5">
                            <input id="remember" aria-describedby="remember" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
                          </div>
                          <div class="ml-3 text-sm">
                            <label for="remember" class="text-gray-500 dark:text-gray-300">Remember me</label>
                          </div>
                      </div>
                  </div>
                  <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Sign in</button>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      Don’t have an account yet? <a href="<%= register_url %>" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>

authentication/app/views/user/new.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
          <img class="w-8 h-8 mr-2" src="https://i.ibb.co/PMNCc2v/Screen-Shot-2022-10-11-at-15-08-55.png" alt="logo">
          100Projects    
      </a>
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <% if @user.errors.any? %>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li class="text-red-700"><%= msg %></li> 
              <% end %>
            </ul>
          <% end %>
              <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                  Create an account
              </h1>
              <form class="space-y-4 md:space-y-6" action="/user" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                  <div>
                      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                      <input type="email" name="user[email]" value="<%= @user.email %>" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="">
                  </div>
                  <div>
                      <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                      <input type="password" name="user[password]" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                  </div>
                  <div>
                      <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm password</label>
                      <input type="password" name="user[password_confirmation]" id="confirm-password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                  </div>
                  <div class="flex items-start">
                      <div class="flex items-center h-5">
                      <input id="terms" aria-describedby="terms"  name="user[terms]" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
                      </div>
                      <div class="ml-3 text-sm">
 
                        <label for="terms" class="font-light text-gray-500 dark:text-gray-300">I accept the <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
                      </div>
                  </div>
                  <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Create an account</button>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      Already have an account? <a href="<%= login_url %>" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Login here</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>