basictodo/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

basictodo/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  scope :by_user,  lambda{ |user| where(:user_id => user.id)}

  validates :title , presence: true

  has_rich_text :content


end

basictodo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :todo , dependent: :destroy
end

basictodo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.by_user(current_user)
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.by_user(current_user).find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:title, :completed)
  end
end

basictodo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basictodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container   px-5 ">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= render 'partials/navbar' %>>

      <%= yield %>
    </main>
  </body>
</html>

basictodo/app/views/partials/_navbar.html.erb
<% if user_signed_in? %>

  <%= link_to "Logout" , destroy_user_session_path,  data: { "turbo-method": :delete }  %>

  <% else %>

  <%= link_to "login" , new_user_session_path , method: :get %>

<% end %>

basictodo/app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :completed %>
    <%= form.check_box :completed, class: "block mt-2 h-5 w-5" %>
  </div>



  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

basictodo/app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="trix-content">


      <p class="my-5">
        <strong class="block font-medium mb-1">Title:</strong>
        <%= todo.title %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Completed:</strong>
        <%= todo.completed %>
      </p>



      <% if action_name != "show" %>
        <%= link_to "Show this todo", todo, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to 'Edit this todo', edit_todo_path(todo), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
        <hr class="mt-6">
      <% end %>

</div>

basictodo/app/views/todos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>


    <%= render "form", todo: @todo %>

    <%= link_to "Show this todo", @todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

basictodo/app/views/todos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Todos</h1>
    <%= link_to 'New todo', new_todo_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="todos" class="min-w-full">
    <%= render @todos %>
  </div>
</div>